{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- if .Values.scope.singleNamespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "ambassador.rbacName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    product: aes
rules:
  - apiGroups: [""]
    resources:
    {{- if not .Values.scope.singleNamespace }}
    - namespaces
    {{- end }}
    - services
    - secrets
    - endpoints
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "getambassador.io" ]
    resources: [ "*" ]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete" ]

  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "networking.internal.knative.dev"]
    resources: [ "clusteringresses" ]
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "extensions", "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "extensions", "networking.k8s.io" ]
    resources: [ "ingresses/status" ]
    verbs: ["update"]

  {{- if .Values.enableAES }}
  - apiGroups: [""]
    resources: [ "secrets" ]
    verbs: ["get", "list", "watch", "create", "update"]

  - apiGroups: [""]
    resources: [ "events" ]
    verbs: ["get", "list", "watch", "create"]

  - apiGroups: ["coordination.k8s.io"]
    resources: [ "leases" ]
    verbs: ["get", "create", "update"]

  - apiGroups: [""]
    resources: [ "endpoints" ]
    verbs: ["get", "list", "watch", "create", "update"]

  # extra permissions for kale
  - apiGroups: [""]
    resources: [ "services" ]
    verbs: [ "get", "list", "create", "patch", "delete", "watch" ]
  - apiGroups: ["apps"]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "create", "patch", "delete", "watch" ]
  - apiGroups: ["batch"]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "create", "patch", "delete", "watch" ]
  - apiGroups: [""]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [""]
    resources: [ "pods/log" ]
    verbs: [ "get" ]
  {{- end }}

  {{- if .Values.rbac.podSecurityPolicies }}
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      {{- toYaml .Values.rbac.podSecurityPolicies | nindent 6 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- if .Values.scope.singleNamespace }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "ambassador.rbacName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.scope.singleNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "ambassador.rbacName" . }}
subjects:
  - name: {{ include "ambassador.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
{{- end -}}
